<?php
/**
 * CommercialOfferSection
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  InfracorpExtranetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Prizz-Telecom Extranet API
 *
 * Prizz-Telecom Extranet API https://dev.prizz-telecom.fr/
 *
 * The version of the OpenAPI document: 1.2.16
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace InfracorpExtranetClient\Model;

use \ArrayAccess;
use \InfracorpExtranetClient\ObjectSerializer;

/**
 * CommercialOfferSection Class Doc Comment
 *
 * @category Class
 * @package  InfracorpExtranetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CommercialOfferSection implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CommercialOfferSection';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'available_workflows' => 'string[]',
        'id' => 'int',
        'name' => 'string',
        'rc_total' => 'array<string,int>',
        'rc_total_str' => 'array<string,string>',
        'rc_vat_total' => 'array<string,int>',
        'rc_vat_total_str' => 'array<string,string>',
        'nrc_total' => 'int',
        'nrc_total_str' => 'string',
        'nrc_vat_total' => 'int',
        'nrc_vat_total_str' => 'string',
        'commercial_offer_id' => 'int',
        'client_reference' => 'string',
        'commercial_offer_items' => '\InfracorpExtranetClient\Model\CommercialOfferItem[]',
        'offer' => '\InfracorpExtranetClient\Model\Offer',
        'service_contract' => '\InfracorpExtranetClient\Model\ServiceContract',
        'client_contract' => '\InfracorpExtranetClient\Model\ClientContract',
        'attributes' => 'array<string,mixed>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'available_workflows' => null,
        'id' => null,
        'name' => null,
        'rc_total' => null,
        'rc_total_str' => null,
        'rc_vat_total' => null,
        'rc_vat_total_str' => null,
        'nrc_total' => null,
        'nrc_total_str' => null,
        'nrc_vat_total' => null,
        'nrc_vat_total_str' => null,
        'commercial_offer_id' => null,
        'client_reference' => null,
        'commercial_offer_items' => null,
        'offer' => null,
        'service_contract' => null,
        'client_contract' => null,
        'attributes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'available_workflows' => false,
        'id' => false,
        'name' => false,
        'rc_total' => false,
        'rc_total_str' => false,
        'rc_vat_total' => false,
        'rc_vat_total_str' => false,
        'nrc_total' => true,
        'nrc_total_str' => false,
        'nrc_vat_total' => true,
        'nrc_vat_total_str' => false,
        'commercial_offer_id' => false,
        'client_reference' => true,
        'commercial_offer_items' => false,
        'offer' => false,
        'service_contract' => false,
        'client_contract' => false,
        'attributes' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'available_workflows' => 'availableWorkflows',
        'id' => 'id',
        'name' => 'name',
        'rc_total' => 'rcTotal',
        'rc_total_str' => 'rcTotalStr',
        'rc_vat_total' => 'rcVATTotal',
        'rc_vat_total_str' => 'rcVATTotalStr',
        'nrc_total' => 'nrcTotal',
        'nrc_total_str' => 'nrcTotalStr',
        'nrc_vat_total' => 'nrcVATTotal',
        'nrc_vat_total_str' => 'nrcVATTotalStr',
        'commercial_offer_id' => 'commercialOfferId',
        'client_reference' => 'clientReference',
        'commercial_offer_items' => 'commercialOfferItems',
        'offer' => 'offer',
        'service_contract' => 'serviceContract',
        'client_contract' => 'clientContract',
        'attributes' => 'attributes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'available_workflows' => 'setAvailableWorkflows',
        'id' => 'setId',
        'name' => 'setName',
        'rc_total' => 'setRcTotal',
        'rc_total_str' => 'setRcTotalStr',
        'rc_vat_total' => 'setRcVatTotal',
        'rc_vat_total_str' => 'setRcVatTotalStr',
        'nrc_total' => 'setNrcTotal',
        'nrc_total_str' => 'setNrcTotalStr',
        'nrc_vat_total' => 'setNrcVatTotal',
        'nrc_vat_total_str' => 'setNrcVatTotalStr',
        'commercial_offer_id' => 'setCommercialOfferId',
        'client_reference' => 'setClientReference',
        'commercial_offer_items' => 'setCommercialOfferItems',
        'offer' => 'setOffer',
        'service_contract' => 'setServiceContract',
        'client_contract' => 'setClientContract',
        'attributes' => 'setAttributes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'available_workflows' => 'getAvailableWorkflows',
        'id' => 'getId',
        'name' => 'getName',
        'rc_total' => 'getRcTotal',
        'rc_total_str' => 'getRcTotalStr',
        'rc_vat_total' => 'getRcVatTotal',
        'rc_vat_total_str' => 'getRcVatTotalStr',
        'nrc_total' => 'getNrcTotal',
        'nrc_total_str' => 'getNrcTotalStr',
        'nrc_vat_total' => 'getNrcVatTotal',
        'nrc_vat_total_str' => 'getNrcVatTotalStr',
        'commercial_offer_id' => 'getCommercialOfferId',
        'client_reference' => 'getClientReference',
        'commercial_offer_items' => 'getCommercialOfferItems',
        'offer' => 'getOffer',
        'service_contract' => 'getServiceContract',
        'client_contract' => 'getClientContract',
        'attributes' => 'getAttributes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_CREATE_COMMERCIAL_OFFER_CONTEXT = 'Infracorp\\Services\\Workflow\\ClientLegalEntity\\CreateCommercialOffer\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_SUBMIT_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\Submit\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_SIGN_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\Sign\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_RENAME_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\Rename\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_ADD_SECTION_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\AddSection\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_REMOVE_SECTION_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\RemoveSection\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_RENAME_SECTION_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\RenameSection\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_UPDATE_OFFER_ITEM_IN_OFFER_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\UpdateOfferItemInOffer\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_SET_OFFER_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\SetOffer\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMENT_ADD_COMMENT_CONTEXT = 'Infracorp\\Services\\Workflow\\Comment\\AddComment\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMENT_SUBSCRIBE_THREAD_CONTEXT = 'Infracorp\\Services\\Workflow\\Comment\\SubscribeThread\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMENT_UPDATE_COMMENT_CONTEXT = 'Infracorp\\Services\\Workflow\\Comment\\UpdateComment\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMENT_UPDATE_THREAD_CONTEXT = 'Infracorp\\Services\\Workflow\\Comment\\UpdateThread\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_CREATE_COMMENT_THREAD_CONTEXT = 'Infracorp\\Services\\Workflow\\ClientLegalEntity\\CreateCommentThread\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_CREATE_COMMENT_THREAD_CONTEXT = 'Infracorp\\Services\\Workflow\\ServiceContract\\CreateCommentThread\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_INVOICE_CREATE_COMMENT_THREAD_CONTEXT = 'Infracorp\\Services\\Workflow\\Invoice\\CreateCommentThread\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_CREATE_COMMENT_THREAD_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\CreateCommentThread\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_USERS_CREATE_TOKEN_CONTEXT = 'Infracorp\\Services\\Workflow\\Users\\CreateToken\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_USERS_REVOKE_TOKEN_CONTEXT = 'Infracorp\\Services\\Workflow\\Users\\RevokeToken\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_UPDATE_SUBSCRIBERS_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\UpdateSubscribers\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_ADD_ITEM_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\AddItem\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_REMOVE_ITEM_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\RemoveItem\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_UPDATE_SECTION_ITEMS_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\UpdateSectionItems\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_ASSIGN_CONTACT_CONTEXT = 'Infracorp\\Services\\Workflow\\ClientLegalEntity\\AssignContact\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_ADD_CONTACT_CONTEXT = 'Infracorp\\Services\\Workflow\\ClientLegalEntity\\AddContact\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_CONTACT_SWITCH_ACTIVE_CONTEXT = 'Infracorp\\Services\\Workflow\\ClientLegalEntityContact\\SwitchActive\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CONTACT_UPDATE_CONTEXT = 'Infracorp\\Services\\Workflow\\Contact\\Update\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_UPDATE_DESCRIPTION_CONTEXT = 'Infracorp\\Services\\Workflow\\ServiceContract\\UpdateDescription\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_UPDATE_CLIENT_REF_CONTEXT = 'Infracorp\\Services\\Workflow\\ServiceContract\\UpdateClientRef\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_ACTIVATION_SETUP_L2_CONTEXT = 'Infracorp\\Services\\Workflow\\ServiceContract\\Activation\\SetupL2\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_UPDATE_CLIENT_REF_SECTION_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\UpdateClientRefSection\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_ASSIGN_CONTACT_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\AssignContact\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_ASSIGN_CONTACT_CONTEXT = 'Infracorp\\Services\\Workflow\\ServiceContract\\AssignContact\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_CONTACT_SWITCH_ACTIVE_CONTEXT = 'Infracorp\\Services\\Workflow\\ServiceContract\\Contact\\SwitchActive\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_CONTACT_SWITCH_ACTIVE_CONTEXT = 'Infracorp\\Services\\Workflow\\CommercialOffer\\Contact\\SwitchActive\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_USERS_SWITCH_ACTIVE_ROLE_CONTEXT = 'Infracorp\\Services\\Workflow\\Users\\SwitchActiveRole\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_ADD_USER_ROLE_CONTEXT = 'Infracorp\\Services\\Workflow\\ClientLegalEntity\\AddUserRole\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_APPOINTMENT_CHANGE_CONTACT_CONTEXT = 'Infracorp\\Services\\Workflow\\Appointment\\ChangeContact\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_APPOINTMENT_CUSTOMER_CANCEL_CONTEXT = 'Infracorp\\Services\\Workflow\\Appointment\\CustomerCancel\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_APPOINTMENT_CUSTOMER_CONFIRM_CONTEXT = 'Infracorp\\Services\\Workflow\\Appointment\\CustomerConfirm\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_MIGRATE_COAX_TO_L2_PREMIUM_CONTEXT = 'Infracorp\\Services\\Workflow\\ServiceContract\\MigrateCoaxToL2Premium\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_CONTRACT_CHANGE_CLIENT_REFERENCE_CONTEXT = 'Infracorp\\Services\\Workflow\\ClientContract\\ChangeClientReference\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_CONTRACT_DEFAULT_DELIVERY_DOOR_CONTEXT = 'Infracorp\\Services\\Workflow\\ClientContract\\DefaultDeliveryDoor\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_CONTRACT_SFR_FON69_CONTEXT = 'Infracorp\\Services\\Workflow\\ClientContract\\SfrFon69\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_UPLOAD_ATTACHMENT_CONTEXT = 'Infracorp\\Services\\Workflow\\ServiceContract\\UploadAttachment\\Context';
    public const AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_CONTRACT_EXPORT_COMBINATIONS_CONTEXT = 'Infracorp\\Services\\Workflow\\ClientContract\\ExportCombinations\\Context';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAvailableWorkflowsAllowableValues()
    {
        return [
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_CREATE_COMMERCIAL_OFFER_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_SUBMIT_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_SIGN_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_RENAME_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_ADD_SECTION_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_REMOVE_SECTION_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_RENAME_SECTION_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_UPDATE_OFFER_ITEM_IN_OFFER_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_SET_OFFER_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMENT_ADD_COMMENT_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMENT_SUBSCRIBE_THREAD_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMENT_UPDATE_COMMENT_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMENT_UPDATE_THREAD_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_CREATE_COMMENT_THREAD_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_CREATE_COMMENT_THREAD_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_INVOICE_CREATE_COMMENT_THREAD_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_CREATE_COMMENT_THREAD_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_USERS_CREATE_TOKEN_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_USERS_REVOKE_TOKEN_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_UPDATE_SUBSCRIBERS_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_ADD_ITEM_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_REMOVE_ITEM_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_UPDATE_SECTION_ITEMS_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_ASSIGN_CONTACT_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_ADD_CONTACT_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_CONTACT_SWITCH_ACTIVE_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CONTACT_UPDATE_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_UPDATE_DESCRIPTION_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_UPDATE_CLIENT_REF_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_ACTIVATION_SETUP_L2_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_UPDATE_CLIENT_REF_SECTION_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_ASSIGN_CONTACT_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_ASSIGN_CONTACT_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_CONTACT_SWITCH_ACTIVE_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_COMMERCIAL_OFFER_CONTACT_SWITCH_ACTIVE_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_USERS_SWITCH_ACTIVE_ROLE_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_LEGAL_ENTITY_ADD_USER_ROLE_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_APPOINTMENT_CHANGE_CONTACT_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_APPOINTMENT_CUSTOMER_CANCEL_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_APPOINTMENT_CUSTOMER_CONFIRM_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_MIGRATE_COAX_TO_L2_PREMIUM_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_CONTRACT_CHANGE_CLIENT_REFERENCE_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_CONTRACT_DEFAULT_DELIVERY_DOOR_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_CONTRACT_SFR_FON69_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_SERVICE_CONTRACT_UPLOAD_ATTACHMENT_CONTEXT,
            self::AVAILABLE_WORKFLOWS_INFRACORP_SERVICES_WORKFLOW_CLIENT_CONTRACT_EXPORT_COMBINATIONS_CONTEXT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('available_workflows', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('rc_total', $data ?? [], null);
        $this->setIfExists('rc_total_str', $data ?? [], null);
        $this->setIfExists('rc_vat_total', $data ?? [], null);
        $this->setIfExists('rc_vat_total_str', $data ?? [], null);
        $this->setIfExists('nrc_total', $data ?? [], null);
        $this->setIfExists('nrc_total_str', $data ?? [], null);
        $this->setIfExists('nrc_vat_total', $data ?? [], null);
        $this->setIfExists('nrc_vat_total_str', $data ?? [], null);
        $this->setIfExists('commercial_offer_id', $data ?? [], null);
        $this->setIfExists('client_reference', $data ?? [], null);
        $this->setIfExists('commercial_offer_items', $data ?? [], null);
        $this->setIfExists('offer', $data ?? [], null);
        $this->setIfExists('service_contract', $data ?? [], null);
        $this->setIfExists('client_contract', $data ?? [], null);
        $this->setIfExists('attributes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets available_workflows
     *
     * @return string[]|null
     */
    public function getAvailableWorkflows()
    {
        return $this->container['available_workflows'];
    }

    /**
     * Sets available_workflows
     *
     * @param string[]|null $available_workflows liste des processus disponible pour l'objet
     *
     * @return self
     */
    public function setAvailableWorkflows($available_workflows)
    {
        if (is_null($available_workflows)) {
            throw new \InvalidArgumentException('non-nullable available_workflows cannot be null');
        }
        $allowedValues = $this->getAvailableWorkflowsAllowableValues();
        if (array_diff($available_workflows, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'available_workflows', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['available_workflows'] = $available_workflows;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets rc_total
     *
     * @return array<string,int>|null
     */
    public function getRcTotal()
    {
        return $this->container['rc_total'];
    }

    /**
     * Sets rc_total
     *
     * @param array<string,int>|null $rc_total rc_total
     *
     * @return self
     */
    public function setRcTotal($rc_total)
    {
        if (is_null($rc_total)) {
            throw new \InvalidArgumentException('non-nullable rc_total cannot be null');
        }
        $this->container['rc_total'] = $rc_total;

        return $this;
    }

    /**
     * Gets rc_total_str
     *
     * @return array<string,string>|null
     */
    public function getRcTotalStr()
    {
        return $this->container['rc_total_str'];
    }

    /**
     * Sets rc_total_str
     *
     * @param array<string,string>|null $rc_total_str rc_total_str
     *
     * @return self
     */
    public function setRcTotalStr($rc_total_str)
    {
        if (is_null($rc_total_str)) {
            throw new \InvalidArgumentException('non-nullable rc_total_str cannot be null');
        }
        $this->container['rc_total_str'] = $rc_total_str;

        return $this;
    }

    /**
     * Gets rc_vat_total
     *
     * @return array<string,int>|null
     */
    public function getRcVatTotal()
    {
        return $this->container['rc_vat_total'];
    }

    /**
     * Sets rc_vat_total
     *
     * @param array<string,int>|null $rc_vat_total rc_vat_total
     *
     * @return self
     */
    public function setRcVatTotal($rc_vat_total)
    {
        if (is_null($rc_vat_total)) {
            throw new \InvalidArgumentException('non-nullable rc_vat_total cannot be null');
        }
        $this->container['rc_vat_total'] = $rc_vat_total;

        return $this;
    }

    /**
     * Gets rc_vat_total_str
     *
     * @return array<string,string>|null
     */
    public function getRcVatTotalStr()
    {
        return $this->container['rc_vat_total_str'];
    }

    /**
     * Sets rc_vat_total_str
     *
     * @param array<string,string>|null $rc_vat_total_str rc_vat_total_str
     *
     * @return self
     */
    public function setRcVatTotalStr($rc_vat_total_str)
    {
        if (is_null($rc_vat_total_str)) {
            throw new \InvalidArgumentException('non-nullable rc_vat_total_str cannot be null');
        }
        $this->container['rc_vat_total_str'] = $rc_vat_total_str;

        return $this;
    }

    /**
     * Gets nrc_total
     *
     * @return int|null
     */
    public function getNrcTotal()
    {
        return $this->container['nrc_total'];
    }

    /**
     * Sets nrc_total
     *
     * @param int|null $nrc_total nrc_total
     *
     * @return self
     */
    public function setNrcTotal($nrc_total)
    {
        if (is_null($nrc_total)) {
            array_push($this->openAPINullablesSetToNull, 'nrc_total');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nrc_total', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nrc_total'] = $nrc_total;

        return $this;
    }

    /**
     * Gets nrc_total_str
     *
     * @return string|null
     */
    public function getNrcTotalStr()
    {
        return $this->container['nrc_total_str'];
    }

    /**
     * Sets nrc_total_str
     *
     * @param string|null $nrc_total_str nrc_total_str
     *
     * @return self
     */
    public function setNrcTotalStr($nrc_total_str)
    {
        if (is_null($nrc_total_str)) {
            throw new \InvalidArgumentException('non-nullable nrc_total_str cannot be null');
        }
        $this->container['nrc_total_str'] = $nrc_total_str;

        return $this;
    }

    /**
     * Gets nrc_vat_total
     *
     * @return int|null
     */
    public function getNrcVatTotal()
    {
        return $this->container['nrc_vat_total'];
    }

    /**
     * Sets nrc_vat_total
     *
     * @param int|null $nrc_vat_total nrc_vat_total
     *
     * @return self
     */
    public function setNrcVatTotal($nrc_vat_total)
    {
        if (is_null($nrc_vat_total)) {
            array_push($this->openAPINullablesSetToNull, 'nrc_vat_total');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nrc_vat_total', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nrc_vat_total'] = $nrc_vat_total;

        return $this;
    }

    /**
     * Gets nrc_vat_total_str
     *
     * @return string|null
     */
    public function getNrcVatTotalStr()
    {
        return $this->container['nrc_vat_total_str'];
    }

    /**
     * Sets nrc_vat_total_str
     *
     * @param string|null $nrc_vat_total_str nrc_vat_total_str
     *
     * @return self
     */
    public function setNrcVatTotalStr($nrc_vat_total_str)
    {
        if (is_null($nrc_vat_total_str)) {
            throw new \InvalidArgumentException('non-nullable nrc_vat_total_str cannot be null');
        }
        $this->container['nrc_vat_total_str'] = $nrc_vat_total_str;

        return $this;
    }

    /**
     * Gets commercial_offer_id
     *
     * @return int|null
     */
    public function getCommercialOfferId()
    {
        return $this->container['commercial_offer_id'];
    }

    /**
     * Sets commercial_offer_id
     *
     * @param int|null $commercial_offer_id commercial_offer_id
     *
     * @return self
     */
    public function setCommercialOfferId($commercial_offer_id)
    {
        if (is_null($commercial_offer_id)) {
            throw new \InvalidArgumentException('non-nullable commercial_offer_id cannot be null');
        }
        $this->container['commercial_offer_id'] = $commercial_offer_id;

        return $this;
    }

    /**
     * Gets client_reference
     *
     * @return string|null
     */
    public function getClientReference()
    {
        return $this->container['client_reference'];
    }

    /**
     * Sets client_reference
     *
     * @param string|null $client_reference client_reference
     *
     * @return self
     */
    public function setClientReference($client_reference)
    {
        if (is_null($client_reference)) {
            array_push($this->openAPINullablesSetToNull, 'client_reference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('client_reference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['client_reference'] = $client_reference;

        return $this;
    }

    /**
     * Gets commercial_offer_items
     *
     * @return \InfracorpExtranetClient\Model\CommercialOfferItem[]|null
     */
    public function getCommercialOfferItems()
    {
        return $this->container['commercial_offer_items'];
    }

    /**
     * Sets commercial_offer_items
     *
     * @param \InfracorpExtranetClient\Model\CommercialOfferItem[]|null $commercial_offer_items commercial_offer_items
     *
     * @return self
     */
    public function setCommercialOfferItems($commercial_offer_items)
    {
        if (is_null($commercial_offer_items)) {
            throw new \InvalidArgumentException('non-nullable commercial_offer_items cannot be null');
        }
        $this->container['commercial_offer_items'] = $commercial_offer_items;

        return $this;
    }

    /**
     * Gets offer
     *
     * @return \InfracorpExtranetClient\Model\Offer|null
     */
    public function getOffer()
    {
        return $this->container['offer'];
    }

    /**
     * Sets offer
     *
     * @param \InfracorpExtranetClient\Model\Offer|null $offer offer
     *
     * @return self
     */
    public function setOffer($offer)
    {
        if (is_null($offer)) {
            throw new \InvalidArgumentException('non-nullable offer cannot be null');
        }
        $this->container['offer'] = $offer;

        return $this;
    }

    /**
     * Gets service_contract
     *
     * @return \InfracorpExtranetClient\Model\ServiceContract|null
     */
    public function getServiceContract()
    {
        return $this->container['service_contract'];
    }

    /**
     * Sets service_contract
     *
     * @param \InfracorpExtranetClient\Model\ServiceContract|null $service_contract service_contract
     *
     * @return self
     */
    public function setServiceContract($service_contract)
    {
        if (is_null($service_contract)) {
            throw new \InvalidArgumentException('non-nullable service_contract cannot be null');
        }
        $this->container['service_contract'] = $service_contract;

        return $this;
    }

    /**
     * Gets client_contract
     *
     * @return \InfracorpExtranetClient\Model\ClientContract|null
     */
    public function getClientContract()
    {
        return $this->container['client_contract'];
    }

    /**
     * Sets client_contract
     *
     * @param \InfracorpExtranetClient\Model\ClientContract|null $client_contract client_contract
     *
     * @return self
     */
    public function setClientContract($client_contract)
    {
        if (is_null($client_contract)) {
            throw new \InvalidArgumentException('non-nullable client_contract cannot be null');
        }
        $this->container['client_contract'] = $client_contract;

        return $this;
    }

    /**
     * Gets attributes
     *
     * @return array<string,mixed>|null
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param array<string,mixed>|null $attributes attributes
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        if (is_null($attributes)) {
            throw new \InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


