<?php
/**
 * EligibilityResultPriceListItemsGroupsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  InfracorpExtranetClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Prizz-Telecom Extranet API
 *
 * Prizz-Telecom Extranet API https://dev.prizz-telecom.fr/
 *
 * The version of the OpenAPI document: 1.2.21
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace InfracorpExtranetClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EligibilityResultPriceListItemsGroupsTest Class Doc Comment
 *
 * @category    Class
 * @description Price list items grouped by product group
 * @package     InfracorpExtranetClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EligibilityResultPriceListItemsGroupsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EligibilityResultPriceListItemsGroups"
     */
    public function testEligibilityResultPriceListItemsGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "main"
     */
    public function testPropertyMain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bandwidth"
     */
    public function testPropertyBandwidth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "commitment"
     */
    public function testPropertyCommitment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "grt"
     */
    public function testPropertyGrt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nrc"
     */
    public function testPropertyNrc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fiber_count"
     */
    public function testPropertyFiberCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "extremity_site_a"
     */
    public function testPropertyExtremitySiteA()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "extremity_site_b"
     */
    public function testPropertyExtremitySiteB()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "maintenance"
     */
    public function testPropertyMaintenance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subnet"
     */
    public function testPropertySubnet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "national"
     */
    public function testPropertyNational()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "racco_event"
     */
    public function testPropertyRaccoEvent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
